In [1]:
import pandas as pd
## 0. 打印设置
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)  ## 显示全部结果，不带省略点
# pd.set_option('display.width', 1000)
pd.set_option('display.float_format', '{:.0f}'.format)

In [2]:
X_train = pd.read_csv(r"data/train.csv")

In [3]:
X_train

,policy_id,age,customer_months,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,insured_occupation,insured_hobbies,insured_relationship,capital-gains,capital-loss,incident_date,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,incident_hour_of_the_day,number_of_vehicles_involved,property_damage,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud
0,122576,37,189,2013/8/21,C,500/1000,1000,1466,5000000,455456,FEMALE,Masters,protective-serv,reading,not-in-family,62203,0,2014/12/22,Single Vehicle Collision,Side Collision,Total Loss,Ambulance,S5,Riverwood,21,1,?,0,3,?,54930,6029,5752,44452,Nissan,Maxima,2000,0
1,937713,44,234,1998/1/4,B,250/500,500,821,0,591805,MALE,JD,craft-repair,polo,other-relative,31606,0,2015/2/18,Multi-vehicle Collision,Side Collision,Minor Damage,Other,S5,Springfield,4,3,?,2,1,YES,50680,5376,10156,37347,Honda,Civic,1996,0
2,680237,33,23,1996/2/6,B,500/1000,1000,1844,0,442490,FEMALE,High School,machine-op-inspct,skydiving,wife,0,-43166,2015/1/18,Single Vehicle Collision,Side Collision,Total Loss,Police,S3,Northbend,0,1,?,2,1,NO,47829,4460,9247,33644,Jeep,Wrangler,2002,0
3,513080,42,210,2008/11/14,A,500/1000,500,1867,0,439408,MALE,JD,transport-moving,video-games,own-child,0,-49440,2015/2/2,Multi-vehicle Collision,Front Collision,Major Damage,Fire,S3,Northbend,20,3,YES,2,2,YES,68862,11043,5955,53548,Suburu,Legacy,2003,1
4,192875,29,81,2002/1/8,A,100/300,1000,816,0,640575,FEMALE,MD,craft-repair,video-games,own-child,75296,-73689,2015/2/9,Multi-vehicle Collision,Rear Collision,Total Loss,Fire,S2,Northbend,9,3,YES,2,1,YES,59726,5617,10301,41550,Ford,F150,2004,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1008425,37,196,1997/6/29,C,250/500,500,1301,0,474615,MALE,JD,tech-support,video-games,wife,47627,0,2015/1/18,Single Vehicle Collision,Front Collision,Major Damage,Ambulance,S5,Columbus,4,1,?,0,3,NO,61433,10436,11432,39745,Nissan,Pathfinder,2011,1
696,770702,43,229,2001/5/29,A,250/500,500,1435,8000000,444476,MALE,College,machine-op-inspct,golf,husband,0,-32289,2015/1/13,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S1,Arlington,17,3,NO,0,1,?,68623,6798,14557,50606,Volkswagen,Passat,2013,1
697,755099,35,209,2003/1/11,C,100/300,500,1639,0,639608,FEMALE,College,transport-moving,golf,not-in-family,0,-40797,2015/3/5,Multi-vehicle Collision,Rear Collision,Minor Damage,Fire,S2,Riverwood,7,3,NO,2,0,YES,58033,9129,4598,40740,Mercedes,C300,2002,0
698,693804,44,275,2003/7/22,B,500/1000,2000,1042,0,432061,FEMALE,Associate,machine-op-inspct,paintball,other-relative,46822,0,2015/1/9,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S5,Northbend,20,3,?,1,0,NO,35253,7359,3464,24677,Audi,A3,2007,1
699,598086,47,263,1996/8/15,C,500/1000,500,1283,0,433809,FEMALE,High School,machine-op-inspct,sleeping,wife,54087,-61343,2015/1/8,Multi-vehicle Collision,Side Collision,Total Loss,Police,S4,Hillsdale,5,3,?,0,0,NO,24320,2250,4285,18092,Suburu,Forrestor,2008,0

In [4]:
## 空值数量
X_train.isnull().sum()

policy_id                      0
age                            0
customer_months                0
policy_bind_date               0
policy_state                   0
policy_csl                     0
policy_deductable              0
policy_annual_premium          0
umbrella_limit                 0
insured_zip                    0
insured_sex                    0
insured_education_level        0
insured_occupation             0
insured_hobbies                0
insured_relationship           0
capital-gains                  0
capital-loss                   0
incident_date                  0
incident_type                  0
collision_type                 0
incident_severity              0
authorities_contacted          0
incident_state                 0
incident_city                  0
incident_hour_of_the_day       0
number_of_vehicles_involved    0
property_damage                0
bodily_injuries                0
witnesses                      0
police_report_available        0
total_claim_amount             0
injury_claim                   0
property_claim                 0
vehicle_claim                  0
auto_make                      0
auto_model                     0
auto_year                      0
fraud                          0
dtype: int64

In [5]:
X_train[['policy_id','age','customer_months','policy_bind_date','policy_state']]

     policy_id  age  customer_months policy_bind_date policy_state
0       122576   37              189        2013/8/21            C
1       937713   44              234         1998/1/4            B
2       680237   33               23         1996/2/6            B
3       513080   42              210       2008/11/14            A
4       192875   29               81         2002/1/8            A
..         ...  ...              ...              ...          ...
695    1008425   37              196        1997/6/29            C
696     770702   43              229        2001/5/29            A
697     755099   35              209        2003/1/11            C
698     693804   44              275        2003/7/22            B
699     598086   47              263        1996/8/15            C

[700 rows x 5 columns]