In [2]:
import pandas as pd
from lightgbm.sklearn import LGBMClassifier
from sklearn.metrics import accuracy_score, auc, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
## 0. 打印设置
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)  ## 显示全部结果，不带省略点
# pd.set_option('display.width', 1000)
pd.set_option('display.float_format', '{:.0f}'.format)

In [3]:
## 1.1 读取数据
train_Base = pd.read_csv(r"data/train.csv")
test_Base = pd.read_csv(r"data/test.csv")

In [4]:
## 1.2 数据合并
data = pd.concat([test_Base, train_Base], axis=0)
data

,policy_id,age,customer_months,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,insured_occupation,insured_hobbies,insured_relationship,capital-gains,capital-loss,incident_date,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,incident_hour_of_the_day,number_of_vehicles_involved,property_damage,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud
0,681822,60,473,2002-12-17,B,500/1000,1000,1135,0,445975,FEMALE,MD,exec-managerial,camping,other-relative,0,-44262,2015-01-31,Multi-vehicle Collision,Rear Collision,Total Loss,Other,S2,Arlington,9,2,?,0,3,?,53253,5212,10251,39503,Saab,95,2006,nan
1,301288,36,173,1994-01-15,B,100/300,1000,916,0,469238,FEMALE,Masters,exec-managerial,camping,other-relative,0,-38591,2015-01-04,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S5,Springfield,22,3,?,0,0,NO,69401,8309,8439,50012,Mercedes,ML350,2008,nan
2,212001,36,147,1995-12-19,B,500/1000,1000,1176,5000000,595953,FEMALE,MD,adm-clerical,hiking,own-child,56753,0,2015-02-09,Single Vehicle Collision,Side Collision,Total Loss,Police,S6,Northbrook,0,1,NO,2,0,NO,63919,5572,11477,42801,Dodge,Neon,2009,nan
3,797680,24,71,1992-06-20,C,500/1000,500,1472,0,613103,FEMALE,High School,armed-forces,yachting,other-relative,0,0,2015-01-15,Multi-vehicle Collision,Rear Collision,Minor Damage,Police,S1,Springfield,23,3,?,0,0,NO,63173,12027,6500,43423,Dodge,RAM,2012,nan
4,789334,39,230,1996-11-28,C,250/500,1000,1159,4000000,581581,FEMALE,Masters,exec-managerial,reading,wife,0,-62877,2015-01-08,Parked Car,?,Minor Damage,Police,S1,Springfield,17,1,YES,0,0,?,8847,904,1786,6138,Accura,RSX,2003,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1008425,37,196,1997-06-29,C,250/500,500,1301,0,474615,MALE,JD,tech-support,video-games,wife,47627,0,2015-01-18,Single Vehicle Collision,Front Collision,Major Damage,Ambulance,S5,Columbus,4,1,?,0,3,NO,61433,10436,11432,39745,Nissan,Pathfinder,2011,1
696,770702,43,229,2001-05-29,A,250/500,500,1435,8000000,444476,MALE,College,machine-op-inspct,golf,husband,0,-32289,2015-01-13,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S1,Arlington,17,3,NO,0,1,?,68623,6798,14557,50606,Volkswagen,Passat,2013,1
697,755099,35,209,2003-01-11,C,100/300,500,1639,0,639608,FEMALE,College,transport-moving,golf,not-in-family,0,-40797,2015-03-05,Multi-vehicle Collision,Rear Collision,Minor Damage,Fire,S2,Riverwood,7,3,NO,2,0,YES,58033,9129,4598,40740,Mercedes,C300,2002,0
698,693804,44,275,2003-07-22,B,500/1000,2000,1042,0,432061,FEMALE,Associate,machine-op-inspct,paintball,other-relative,46822,0,2015-01-09,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S5,Northbend,20,3,?,1,0,NO,35253,7359,3464,24677,Audi,A3,2007,1
699,598086,47,263,1996-08-15,C,500/1000,500,1283,0,433809,FEMALE,High School,machine-op-inspct,sleeping,wife,54087,-61343,2015-01-08,Multi-vehicle Collision,Side Collision,Total Loss,Police,S4,Hillsdale,5,3,?,0,0,NO,24320,2250,4285,18092,Suburu,Forrestor,2008,0

In [5]:
## 1.3 数据清洗
## 1.3.1 索引完善
data.index = range(len(data))

In [6]:
## 1.4 数据探索
## 1.4.1 空值数量
data.isnull().sum()

policy_id                        0
age                              0
customer_months                  0
policy_bind_date                 0
policy_state                     0
policy_csl                       0
policy_deductable                0
policy_annual_premium            0
umbrella_limit                   0
insured_zip                      0
insured_sex                      0
insured_education_level          0
insured_occupation               0
insured_hobbies                  0
insured_relationship             0
capital-gains                    0
capital-loss                     0
incident_date                    0
incident_type                    0
collision_type                   0
incident_severity                0
authorities_contacted            0
incident_state                   0
incident_city                    0
incident_hour_of_the_day         0
number_of_vehicles_involved      0
property_damage                  0
bodily_injuries                  0
witnesses                        0
police_report_available          0
total_claim_amount               0
injury_claim                     0
property_claim                   0
vehicle_claim                    0
auto_make                        0
auto_model                       0
auto_year                        0
fraud                          300
dtype: int64

In [7]:
# 1.4.2 唯一值个数
for col in data.columns:
    print(col, data[col].nunique())

policy_id 1000
age 45
customer_months 385
policy_bind_date 955
policy_state 3
policy_csl 3
policy_deductable 3
policy_annual_premium 996
umbrella_limit 11
insured_zip 999
insured_sex 2
insured_education_level 7
insured_occupation 14
insured_hobbies 20
insured_relationship 6
capital-gains 490
capital-loss 525
incident_date 113
incident_type 4
collision_type 4
incident_severity 4
authorities_contacted 5
incident_state 7
incident_city 7
incident_hour_of_the_day 24
number_of_vehicles_involved 4
property_damage 3
bodily_injuries 3
witnesses 4
police_report_available 3
total_claim_amount 989
injury_claim 945
property_claim 931
vehicle_claim 991
auto_make 14
auto_model 39
auto_year 21
fraud 2

In [8]:
## 1.4.3 字符串的字段，唯一值统计
cat_columns = data.select_dtypes(include='object').columns  

column_name = []
unique_value = []
 
for col in cat_columns:
    column_name.append(col)
    unique_value.append(data[col].nunique())

df = pd.DataFrame()
df['col_name'] = column_name
df['value'] = unique_value
df = df.sort_values('value', ascending=False)
 
df

                   col_name  value
0          policy_bind_date    955
8             incident_date    113
18               auto_model     39
6           insured_hobbies     20
5        insured_occupation     14
17                auto_make     14
4   insured_education_level      7
13           incident_state      7
14            incident_city      7
7      insured_relationship      6
12    authorities_contacted      5
10           collision_type      4
11        incident_severity      4
9             incident_type      4
2                policy_csl      3
1              policy_state      3
15          property_damage      3
16  police_report_available      3
3               insured_sex      2

In [9]:
## 2 特征工程
## 2.0 特征编码--property_damage、police_report_available
data['property_damage'].value_counts()
data['property_damage'] = data['property_damage'].map({'NO': 0, 'YES': 1, '?': 2})
data['property_damage'].value_counts()

data['police_report_available'].value_counts()
data['police_report_available'] = data['police_report_available'].map({'NO': 0, 'YES': 1, '?': 2})
data['police_report_available'].value_counts()

2    343
0    343
1    314
Name: police_report_available, dtype: int64

In [10]:
## 2.1 特征编码--日期编码
# policy_bind_date, incident_date
data['policy_bind_date'] = pd.to_datetime(data['policy_bind_date'])
data['incident_date'] = pd.to_datetime(data['incident_date'])
 
# 查看最大日期，最小日期
data['policy_bind_date'].min() # 1990-01-08
data['policy_bind_date'].max() # 2015-02-22

data['incident_date'].min() # 2015-01-01
data['incident_date'].max() # 2015-03-01

base_date = data['policy_bind_date'].min()
# 转换为date_diff
data['policy_bind_date_diff'] = (data['policy_bind_date'] - base_date).dt.days
data['incident_date_diff'] = (data['incident_date'] - base_date).dt.days

#去掉原始日期字段 policy_bind_date    incident_date
data.drop(['policy_bind_date', 'incident_date'], axis=1, inplace=True)
data

,policy_id,age,customer_months,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,insured_occupation,insured_hobbies,insured_relationship,capital-gains,capital-loss,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,incident_hour_of_the_day,number_of_vehicles_involved,property_damage,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud,policy_bind_date_diff,incident_date_diff
0,681822,60,473,B,500/1000,1000,1135,0,445975,FEMALE,MD,exec-managerial,camping,other-relative,0,-44262,Multi-vehicle Collision,Rear Collision,Total Loss,Other,S2,Arlington,9,2,2,0,3,2,53253,5212,10251,39503,Saab,95,2006,nan,4740,9168
1,301288,36,173,B,100/300,1000,916,0,469238,FEMALE,Masters,exec-managerial,camping,other-relative,0,-38591,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S5,Springfield,22,3,2,0,0,0,69401,8309,8439,50012,Mercedes,ML350,2008,nan,1482,9141
2,212001,36,147,B,500/1000,1000,1176,5000000,595953,FEMALE,MD,adm-clerical,hiking,own-child,56753,0,Single Vehicle Collision,Side Collision,Total Loss,Police,S6,Northbrook,0,1,0,2,0,0,63919,5572,11477,42801,Dodge,Neon,2009,nan,2185,9177
3,797680,24,71,C,500/1000,500,1472,0,613103,FEMALE,High School,armed-forces,yachting,other-relative,0,0,Multi-vehicle Collision,Rear Collision,Minor Damage,Police,S1,Springfield,23,3,2,0,0,0,63173,12027,6500,43423,Dodge,RAM,2012,nan,908,9152
4,789334,39,230,C,250/500,1000,1159,4000000,581581,FEMALE,Masters,exec-managerial,reading,wife,0,-62877,Parked Car,?,Minor Damage,Police,S1,Springfield,17,1,1,0,0,2,8847,904,1786,6138,Accura,RSX,2003,nan,2530,9145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1008425,37,196,C,250/500,500,1301,0,474615,MALE,JD,tech-support,video-games,wife,47627,0,Single Vehicle Collision,Front Collision,Major Damage,Ambulance,S5,Columbus,4,1,2,0,3,0,61433,10436,11432,39745,Nissan,Pathfinder,2011,1,2743,9155
996,770702,43,229,A,250/500,500,1435,8000000,444476,MALE,College,machine-op-inspct,golf,husband,0,-32289,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S1,Arlington,17,3,0,0,1,2,68623,6798,14557,50606,Volkswagen,Passat,2013,1,4173,9150
997,755099,35,209,C,100/300,500,1639,0,639608,FEMALE,College,transport-moving,golf,not-in-family,0,-40797,Multi-vehicle Collision,Rear Collision,Minor Damage,Fire,S2,Riverwood,7,3,0,2,0,1,58033,9129,4598,40740,Mercedes,C300,2002,0,4765,9201
998,693804,44,275,B,500/1000,2000,1042,0,432061,FEMALE,Associate,machine-op-inspct,paintball,other-relative,46822,0,Multi-vehicle Collision,Rear Collision,Major Damage,Ambulance,S5,Northbend,20,3,2,1,0,0,35253,7359,3464,24677,Audi,A3,2007,1,4957,9146
999,598086,47,263,C,500/1000,500,1283,0,433809,FEMALE,High School,machine-op-inspct,sleeping,wife,54087,-61343,Multi-vehicle Collision,Side Collision,Total Loss,Police,S4,Hillsdale,5,3,2,0,0,0,24320,2250,4285,18092,Suburu,Forrestor,2008,0,2425,9145

In [11]:
## 2.2 去除无关的特征
data.drop(['policy_id'], axis=1, inplace=True)
data.columns

Index(['age', 'customer_months', 'policy_state', 'policy_csl',
       'policy_deductable', 'policy_annual_premium', 'umbrella_limit',
       'insured_zip', 'insured_sex', 'insured_education_level',
       'insured_occupation', 'insured_hobbies', 'insured_relationship',
       'capital-gains', 'capital-loss', 'incident_type', 'collision_type',
       'incident_severity', 'authorities_contacted', 'incident_state',
       'incident_city', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud', 'policy_bind_date_diff',
       'incident_date_diff'],
      dtype='object')

In [12]:
## 2.3 标签编码
cat_columns = data.select_dtypes(include=['object']).columns
le = LabelEncoder()
for col in cat_columns:
    data[col] = le.fit_transform(data[col])
data[cat_columns]

,policy_state,policy_csl,insured_sex,insured_education_level,insured_occupation,insured_hobbies,insured_relationship,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,auto_make,auto_model
0,1,2,0,4,3,4,2,0,2,2,3,1,0,10,3
1,1,0,0,5,3,4,2,0,2,0,0,4,6,8,24
2,1,2,0,4,0,10,3,2,3,2,4,5,4,4,27
3,2,2,0,2,1,19,2,0,2,1,4,0,6,4,30
4,2,1,0,5,3,15,5,1,0,1,4,0,6,0,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,1,1,3,12,18,5,2,1,0,0,4,1,9,29
996,0,1,1,1,6,9,0,0,2,0,0,0,0,13,28
997,2,0,0,1,13,9,1,0,2,1,1,1,5,8,7
998,1,2,0,0,6,13,2,0,2,0,0,4,3,1,4
999,2,2,0,2,6,17,5,0,3,2,4,3,2,11,15

In [13]:
## 2.4 分箱编码

# ## 1）age分箱
# for x in range(10,70,10):
#     train_Base[train_Base['age'].between(x,x+10)].loc[:,['age']]=x

In [14]:
## 3. 数据集切分
## 3.1 切分训练集和测试集
train = data[data['fraud'].notnull()]
test = data[data['fraud'].isnull()]

In [15]:
## 3.2 训练集中，训练集和验证集的划分

# x_train, x_train_01 = train_test_split(train.drop(['fraud'],axis=1), test_size=0.2, random_state=42)  # 25% of remaining data as validation set  
# y_train, y_train_01 = train_test_split(train['fraud'], test_size=0.2, random_state=42)  # Split labels accordingly  

x_train, x_train_01, y_train, y_train_01 = train_test_split(train.drop(['fraud'],axis=1), train['fraud'], test_size=0.3, random_state=1)

In [16]:
## 4. 模型训练
## 4.1 建立模型
gbm = LGBMClassifier(n_estimators=600, learning_rate=0.01, boosting_type='gbdt',  ## 模型训练超参数 调优参考：https://blog.51cto.com/u_16213313/7201851
                     objective='binary',   ## LGBMClassifier详解： https://blog.csdn.net/yeshang_lady/article/details/118638269
                     max_depth=-1,
                     random_state=2022,
                     metric='auc')

In [36]:
# 4.2 模型训练
## train.drop(['fraud'],axis=1) ## axis=0 表示行，axis=1 表示列
gbm.fit(x_train, y_train)

LGBMClassifier(learning_rate=0.01, metric='auc', n_estimators=600,
               objective='binary', random_state=2022)

In [37]:
# 4.3 模型预测，以proba进行提交，结果会更好
y_train_01_pred = gbm.predict_proba(x_train_01)

In [38]:
## 5. 模型评估
## 5.1 评估auc值
auc = roc_auc_score(y_train_01, y_train_01_pred[:,-1]) # 计算auc值
print("auc值:", auc)

## 5.2 概率转换
y_train_01_pred[:, 1][y_train_01_pred[:, 1] > 0.5] = '1'
y_train_01_pred[:, 1][y_train_01_pred[:, 1] <= 0.5] = '0'
y_train_01_pred

## 5.3 评估accuracy，precision，recall，f1
from sklearn.metrics import precision_score, recall_score, f1_score
 
accuracy=accuracy_score(y_train_01, y_train_01_pred[:,-1])  ## 计算准确率
precision = precision_score(y_train_01, y_train_01_pred[:,-1]) # 计算精确率
recall = recall_score(y_train_01, y_train_01_pred[:,-1]) # 计算召回率
f1 = f1_score(y_train_01, y_train_01_pred[:,-1]) # 计算F1值


# 输出计算得到的准确率、召回率和F1值
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

auc值: 0.8622448979591836
Accuracy: 0.8095238095238095
Precision: 0.6666666666666666
Recall: 0.5714285714285714
F1 Score: 0.6153846153846153

In [40]:
# ## 5.1 模型命名，版本控制
# model_name='model_0_86224_base'

In [42]:
## 6 结果输出
## 6.1 test集的预测
# y_test_pred = gbm.predict_proba(test.drop(['fraud'],axis=1))
# y_test_pred[:, 1][y_test_pred[:, 1] > 0.5] = '1'
# y_test_pred[:, 1][y_test_pred[:, 1] <= 0.5] = '0'
# y_test_pred

array([[0.96747996, 0.        ],
       [0.21587384, 1.        ],
       [0.98673083, 0.        ],
       [0.98478039, 0.        ],
       [0.96471509, 0.        ],
       [0.9146069 , 0.        ],
       [0.97079274, 0.        ],
       [0.96803434, 0.        ],
       [0.99554571, 0.        ],
       [0.88304021, 0.        ],
       [0.9959851 , 0.        ],
       [0.95974966, 0.        ],
       [0.2613624 , 1.        ],
       [0.98518623, 0.        ],
       [0.99145713, 0.        ],
       [0.33889417, 1.        ],
       [0.98244624, 0.        ],
       [0.91168157, 0.        ],
       [0.16629331, 1.        ],
       [0.87491679, 0.        ],
       [0.88442368, 0.        ],
       [0.98119372, 0.        ],
       [0.55177523, 0.        ],
       [0.96880901, 0.        ],
       [0.9932192 , 0.        ],
       [0.47305982, 1.        ],
       [0.9976463 , 0.        ],
       [0.98516801, 0.        ],
       [0.19709417, 1.        ],
       [0.96659308, 0.        ],
       [0.79649178, 0.        ],
       [0.98661809, 0.        ],
       [0.23718113, 1.        ],
       [0.95030261, 0.        ],
       [0.99435896, 0.        ],
       [0.97616274, 0.        ],
       [0.12919013, 1.        ],
       [0.99037501, 0.        ],
       [0.98699863, 0.        ],
       [0.97903998, 0.        ],
       [0.40158922, 1.        ],
       [0.984633  , 0.        ],
       [0.98907625, 0.        ],
       [0.9907054 , 0.        ],
       [0.949612  , 0.        ],
       [0.97905688, 0.        ],
       [0.9804799 , 0.        ],
       [0.97292957, 0.        ],
       [0.33841088, 1.        ],
       [0.98988906, 0.        ],
       [0.986005  , 0.        ],
       [0.97473131, 0.        ],
       [0.99553417, 0.        ],
       [0.68993427, 0.        ],
       [0.54317499, 0.        ],
       [0.97174988, 0.        ],
       [0.81807151, 0.        ],
       [0.52129047, 0.        ],
       [0.96333609, 0.        ],
       [0.21535444, 1.        ],
       [0.99507642, 0.        ],
       [0.98838843, 0.        ],
       [0.98246233, 0.        ],
       [0.16045068, 1.        ],
       [0.99302871, 0.        ],
       [0.90722676, 0.        ],
       [0.37293463, 1.        ],
       [0.30241338, 1.        ],
       [0.98963797, 0.        ],
       [0.9870826 , 0.        ],
       [0.99261413, 0.        ],
       [0.95785412, 0.        ],
       [0.28139283, 1.        ],
       [0.27089562, 1.        ],
       [0.98535856, 0.        ],
       [0.99263352, 0.        ],
       [0.92855573, 0.        ],
       [0.99477217, 0.        ],
       [0.21741175, 1.        ],
       [0.94577689, 0.        ],
       [0.97110875, 0.        ],
       [0.98269296, 0.        ],
       [0.49241096, 1.        ],
       [0.98885707, 0.        ],
       [0.9245476 , 0.        ],
       [0.98678233, 0.        ],
       [0.97397912, 0.        ],
       [0.98912259, 0.        ],
       [0.95420014, 0.        ],
       [0.22714258, 1.        ],
       [0.97807684, 0.        ],
       [0.56740017, 0.        ],
       [0.09688792, 1.        ],
       [0.99632191, 0.        ],
       [0.99227247, 0.        ],
       [0.92802375, 0.        ],
       [0.97366921, 0.        ],
       [0.98369014, 0.        ],
       [0.77011946, 0.        ],
       [0.9962665 , 0.        ],
       [0.99101979, 0.        ],
       [0.42397342, 1.        ],
       [0.99545552, 0.        ],
       [0.97708153, 0.        ],
       [0.99589451, 0.        ],
       [0.30500285, 1.        ],
       [0.69679063, 0.        ],
       [0.36342535, 1.        ],
       [0.97319446, 0.        ],
       [0.9502447 , 0.        ],
       [0.91317092, 0.        ],
       [0.98010933, 0.        ],
       [0.98335384, 0.        ],
       [0.97425041, 0.        ],
       [0.99473063, 0.        ],
       [0.80075465, 0.        ],
       [0.1874385 , 1.        ],
       [0.9694313 , 0.        ],
       [0.1817694 , 1.        ],
       [0.96532622, 0.        ],
       [0.97769722, 0.        ],
       [0.97901427, 0.        ],
       [0.4025175 , 1.        ],
       [0.41049472, 1.        ],
       [0.9878964 , 0.        ],
       [0.33429489, 1.        ],
       [0.99034863, 0.        ],
       [0.96221801, 0.        ],
       [0.57128286, 0.        ],
       [0.97163106, 0.        ],
       [0.99165225, 0.        ],
       [0.62432537, 0.        ],
       [0.98038881, 0.        ],
       [0.96248005, 0.        ],
       [0.97765441, 0.        ],
       [0.97659761, 0.        ],
       [0.95068896, 0.        ],
       [0.61796641, 0.        ],
       [0.44498097, 1.        ],
       [0.98315702, 0.        ],
       [0.85836257, 0.        ],
       [0.98405361, 0.        ],
       [0.61924121, 0.        ],
       [0.96086226, 0.        ],
       [0.33922648, 1.        ],
       [0.17533858, 1.        ],
       [0.9860757 , 0.        ],
       [0.93877027, 0.        ],
       [0.8970588 , 0.        ],
       [0.97552559, 0.        ],
       [0.9861327 , 0.        ],
       [0.74139663, 0.        ],
       [0.20381779, 1.        ],
       [0.36505138, 1.        ],
       [0.99630236, 0.        ],
       [0.94267572, 0.        ],
       [0.35874109, 1.        ],
       [0.97618621, 0.        ],
       [0.94047107, 0.        ],
       [0.9677455 , 0.        ],
       [0.12459769, 1.        ],
       [0.96812122, 0.        ],
       [0.45478732, 1.        ],
       [0.47949333, 1.        ],
       [0.10551235, 1.        ],
       [0.39045305, 1.        ],
       [0.98464751, 0.        ],
       [0.97828629, 0.        ],
       [0.19392701, 1.        ],
       [0.98960895, 0.        ],
       [0.99152288, 0.        ],
       [0.96779296, 0.        ],
       [0.79092235, 0.        ],
       [0.47766672, 1.        ],
       [0.89905476, 0.        ],
       [0.40708233, 1.        ],
       [0.93143965, 0.        ],
       [0.97371649, 0.        ],
       [0.99421258, 0.        ],
       [0.98402028, 0.        ],
       [0.94126302, 0.        ],
       [0.99017404, 0.        ],
       [0.98972558, 0.        ],
       [0.9945232 , 0.        ],
       [0.96642528, 0.        ],
       [0.64750501, 0.        ],
       [0.98347252, 0.        ],
       [0.13875407, 1.        ],
       [0.77190288, 0.        ],
       [0.96256227, 0.        ],
       [0.95999194, 0.        ],
       [0.99047469, 0.        ],
       [0.92984408, 0.        ],
       [0.12136406, 1.        ],
       [0.31241001, 1.        ],
       [0.99147138, 0.        ],
       [0.98284768, 0.        ],
       [0.9918629 , 0.        ],
       [0.9839395 , 0.        ],
       [0.24758594, 1.        ],
       [0.97825417, 0.        ],
       [0.92227167, 0.        ],
       [0.09776515, 1.        ],
       [0.86675316, 0.        ],
       [0.98899973, 0.        ],
       [0.99031219, 0.        ],
       [0.93010414, 0.        ],
       [0.95933439, 0.        ],
       [0.90403205, 0.        ],
       [0.97504259, 0.        ],
       [0.9888591 , 0.        ],
       [0.9532283 , 0.        ],
       [0.99687892, 0.        ],
       [0.98822383, 0.        ],
       [0.19130967, 1.        ],
       [0.94750611, 0.        ],
       [0.27779882, 1.        ],
       [0.99573622, 0.        ],
       [0.99405771, 0.        ],
       [0.39720584, 1.        ],
       [0.73660003, 0.        ],
       [0.87515488, 0.        ],
       [0.99703157, 0.        ],
       [0.95358054, 0.        ],
       [0.9540091 , 0.        ],
       [0.33749937, 1.        ],
       [0.89689979, 0.        ],
       [0.91920717, 0.        ],
       [0.09338631, 1.        ],
       [0.88337284, 0.        ],
       [0.9449683 , 0.        ],
       [0.97238935, 0.        ],
       [0.9702175 , 0.        ],
       [0.98906026, 0.        ],
       [0.69884472, 0.        ],
       [0.48718967, 1.        ],
       [0.97483423, 0.        ],
       [0.93422396, 0.        ],
       [0.96797292, 0.        ],
       [0.98745364, 0.        ],
       [0.85325201, 0.        ],
       [0.93981441, 0.        ],
       [0.98952166, 0.        ],
       [0.94213433, 0.        ],
       [0.98239271, 0.        ],
       [0.62566016, 0.        ],
       [0.98949326, 0.        ],
       [0.9469001 , 0.        ],
       [0.97759103, 0.        ],
       [0.98875588, 0.        ],
       [0.7526629 , 0.        ],
       [0.64720557, 0.        ],
       [0.6002454 , 0.        ],
       [0.99214998, 0.        ],
       [0.98770831, 0.        ],
       [0.96155363, 0.        ],
       [0.53008696, 0.        ],
       [0.96020292, 0.        ],
       [0.18658591, 1.        ],
       [0.84787415, 0.        ],
       [0.51812746, 0.        ],
       [0.97407587, 0.        ],
       [0.53947617, 0.        ],
       [0.99358993, 0.        ],
       [0.99069576, 0.        ],
       [0.97281209, 0.        ],
       [0.92382394, 0.        ],
       [0.97486312, 0.        ],
       [0.99305568, 0.        ],
       [0.96574677, 0.        ],
       [0.16042789, 1.        ],
       [0.94577431, 0.        ],
       [0.98366854, 0.        ],
       [0.86967606, 0.        ],
       [0.52125992, 0.        ],
       [0.96446876, 0.        ],
       [0.96589064, 0.        ],
       [0.98863881, 0.        ],
       [0.06138454, 1.        ],
       [0.99076627, 0.        ],
       [0.94080204, 0.        ],
       [0.95506406, 0.        ],
       [0.95790595, 0.        ],
       [0.55443743, 0.        ],
       [0.60041146, 0.        ],
       [0.99646756, 0.        ],
       [0.43631934, 1.        ],
       [0.92903654, 0.        ],
       [0.46925698, 1.        ],
       [0.38886662, 1.        ],
       [0.99549108, 0.        ],
       [0.17269323, 1.        ],
       [0.53560638, 0.        ],
       [0.98326123, 0.        ],
       [0.3517642 , 1.        ],
       [0.99040701, 0.        ],
       [0.988392  , 0.        ],
       [0.99705339, 0.        ],
       [0.96211842, 0.        ],
       [0.9476318 , 0.        ]])

In [43]:
# 6.2 输出结果

# result = pd.read_csv('./data/submission.csv')
# result['fraud'] = y_test_pred[:, 1]
# result.to_csv(f'./data/{model_name}.csv', index=False)

In [23]:
## 7 模型评估结果输出
# evalue_result=pd.read_csv('./data/evalue_result.csv', encoding='utf-8')
# evalue_result

Empty DataFrame
Columns: [model_name, update_time, Accuracy, Precision, Recall, F1 Score, auc, sub_score, update_content]
Index: []

In [25]:
## 5.1 模型评估结果输出
# import datetime 

# new_row = {'model_name': model_name, 'update_time': datetime.datetime.now() , 'Accuracy': accuracy, 'Precision': precision, 'Recall': recall
#  , 'F1 Score': f1, 'auc': auc, 'sub_score': 0.8496, 'update_content': 'base model'}  
# evalue_result.loc[len(evalue_result.index)] = new_row 
# evalue_result
# evalue_result.to_csv('./data/evalue_result.csv', index=False)